import { useParams, useNavigate } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { semestersData } from '../data/coursesData'
import { getCourse, getCourseProgress } from '../api/courses'
import { generateStudyPlan } from '../api/studyplan'
import { Card } from '../components/ui/Card'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Modal } from '../components/ui/Modal'
import { Input } from '../components/ui/Input'

const CATEGORY_MAP = {
  HS: { label: 'Humanities & Social Sciences', variant: 'success' },
  BS: { label: 'Basic Sciences', variant: 'info' },
  ES: { label: 'Engineering Sciences', variant: 'neutral' },
  PC: { label: 'Professional Core', variant: 'info' },
  PE: { label: 'Professional Elective', variant: 'warning' },
  MC: { label: 'Mandatory Course', variant: 'danger' }
};

// Realistic mock responses for AI assistant based on courses
const getAIExplanation = (courseName, unitTitle, topics) => {
  return `### 🧠 AI Concept Explanation: ${unitTitle}
*Generated by Smart Academia Advisor Agent*

This unit covers the foundational elements of **${courseName}**, specifically focusing on **${unitTitle}**. Here is a detailed breakdown of the core concepts:

#### 1. Core Focus Areas
${topics.map((t, idx) => `* **${t}**: This topic addresses the fundamental mechanism of how systems process related inputs. In practice, understanding ${t} allows us to model real-world behaviors and optimize performance limits.`).join('\n')}

#### 2. Key Theoretical Principles
* **Efficiency Bounds**: Every system in this domain operates within defined boundaries of complexity and resource consumption.
* **Modern Adaptations**: Traditional methodologies are increasingly integrated with data-driven AI systems to allow autonomous decision-making.

#### 3. Real-World Applications
* **Industry 4.0/5.0 Integration**: Used to optimize automated assembly lines and supply chains.
* **Predictive Diagnostics**: Critical for predicting failures in electrical, physical, and computational models.

---
*Tip: Try generating a Practice Quiz next to test your understanding of these points!*`;
};

const getAISummary = (courseName, unitTitle, topics) => {
  return `### 📝 Unit Summary: ${unitTitle}
*Quick revision guide compiled by Academic Agent*

#### 📌 Overview
A concise synthesis of **${unitTitle}** in the context of **${courseName}**.

#### 🔑 Key Definitions
${topics.map((t, idx) => `* **${t}**: The core standard governing this section. Critical for mid-term and end-semester evaluations.`).join('\n')}

#### ⚡ Quick Revision Checklist
- [ ] Understand the mathematical proofs behind these concepts.
- [ ] Identify the trade-offs of using these frameworks compared to legacy models.
- [ ] Practice drawing structural diagrams representing these relationships.

---
*Study Goal: Spend 45 minutes reviewing the recommended resources to solidify this summary.*`;
};

const getAIQuiz = (courseName, unitTitle, topics) => {
  // Generate 3 custom questions based on topics
  return {
    title: `⚡ Practice Quiz: ${unitTitle}`,
    questions: [
      {
        question: `Which of the following is the primary challenge when implementing ${topics[0] || 'this concept'}?`,
        options: [
          'High initial computation and latency constraints',
          'Lack of standardized learning outcomes',
          'Incompatibility with modern IDEs',
          'None of the above'
        ],
        answer: 0,
        explanation: 'Most systems in this domain suffer from high resource requirements during initial initialization.'
      },
      {
        question: `How does ${topics[1] || 'the second topic'} directly influence system performance?`,
        options: [
          'It decreases data throughput',
          'It provides a structured framework to minimize error rates and optimize execution',
          'It restricts multi-user access permissions',
          'It disables local caching mechanisms'
        ],
        answer: 1,
        explanation: 'Optimizing this specific concept allows the application to resolve bottlenecks and balance overall loads.'
      },
      {
        question: `In professional practice, what is the best resource to consult for ${topics[2] || 'the final topic'}?`,
        options: [
          'Wikipedia general pages',
          'Official standards documentation and recommended course textbooks',
          'Social media discussion forums',
          'Legacy offline archives'
        ],
        answer: 1,
        explanation: 'Industry standards and peer-reviewed journals are the only source of truth for these advanced subjects.'
      }
    ]
  };
};

export default function CoursePage() {
  const { courseId } = useParams()
  const navigate = useNavigate()
  
  const [course, setCourse] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [expandedUnit, setExpandedUnit] = useState(0) // Default expand Unit I
  
  // Topic statuses local state
  const [topicStatuses, setTopicStatuses] = useState({})
  
  // AI Modal states
  const [showAIModal, setShowAIModal] = useState(false)
  const [aiModalTitle, setAIModalTitle] = useState('')
  const [aiModalContent, setAIModalContent] = useState('')
  const [aiLoading, setAILoading] = useState(false)
  
  // Custom Quiz state
  const [activeQuiz, setActiveQuiz] = useState(null)
  const [selectedAnswers, setSelectedAnswers] = useState({})
  const [quizSubmitted, setQuizSubmitted] = useState(false)
  
  // AI Ask state
  const [aiAskQuery, setAIAskQuery] = useState('')
  const [aiAskChat, setAIAskChat] = useState([])
  const [currentUnitForAsk, setCurrentUnitForAsk] = useState(null)

  // Load course details
  useEffect(() => {
    const loadCourseData = async () => {
      setLoading(true)
      setError('')
      
      try {
        let selectedSemCourse = null;
        
        // 1. Try to find the course in static semestersData
        for (const semNum in semestersData) {
          const found = semestersData[semNum].find(c => c.course_code === courseId);
          if (found) {
            selectedSemCourse = { ...found };
            break;
          }
        }
        
        // 2. If not found statically and courseId is numeric, try database
        if (!selectedSemCourse && /^\d+$/.test(courseId)) {
          try {
            const dbRes = await getCourse(courseId);
            const dbCourse = dbRes.data;
            
            // Try to match DB course code with static data to get 5 units
            for (const semNum in semestersData) {
              const found = semestersData[semNum].find(c => c.course_code === dbCourse.course_code);
              if (found) {
                selectedSemCourse = { ...found, id: dbCourse.id }; // preserve database ID
                break;
              }
            }
            
            // If still no unit mapping, build basic mapping from DB
            if (!selectedSemCourse) {
              selectedSemCourse = {
                course_code: dbCourse.course_code,
                course_name: dbCourse.course_name,
                credits: dbCourse.credits || 3,
                category: 'PC',
                description: dbCourse.description || '',
                units: dbCourse.units?.map((u, idx) => ({
                  unit_number: idx + 1,
                  title: u.title || `Unit ${idx + 1}`,
                  learning_objectives: 'Understand unit fundamentals.',
                  topics: u.topics?.map(t => t.title) || [],
                  subtopics: [],
                  resources: ['Recommended Class Notes']
                })) || []
              };
            }
          } catch (apiErr) {
            console.error("API Fetch failed: ", apiErr);
          }
        }
        
        if (selectedSemCourse) {
          setCourse(selectedSemCourse);
          
          // Load topic statuses from localStorage
          const statuses = {};
          selectedSemCourse.units.forEach((unit, uIdx) => {
            if (unit.topics) {
              unit.topics.forEach((topic, tIdx) => {
                const key = `topic_status_${selectedSemCourse.course_code}_${uIdx}_${tIdx}`;
                statuses[`${uIdx}-${tIdx}`] = localStorage.getItem(key) || 'not_started';
              });
            }
          });
          setTopicStatuses(statuses);
        } else {
          setError('Course not found in the AI & DS curriculum.');
        }
      } catch (err) {
        setError('An error occurred while loading the syllabus.');
      } finally {
        setLoading(false)
      }
    }
    
    loadCourseData();
  }, [courseId])

  // Handle status changes for a topic
  const handleStatusChange = (uIdx, tIdx, newStatus) => {
    if (!course) return;
    const key = `topic_status_${course.course_code}_${uIdx}_${tIdx}`;
    localStorage.setItem(key, newStatus);
    
    setTopicStatuses(prev => ({
      ...prev,
      [`${uIdx}-${tIdx}`]: newStatus
    }));
    
    // Dispatch local storage change event so components re-evaluate
    window.dispatchEvent(new Event('storage'));
  };

  // Compute local course progress
  const getOverallProgress = () => {
    if (!course) return 0;
    let total = 0;
    let completed = 0;
    course.units.forEach((unit, uIdx) => {
      if (unit.topics) {
        unit.topics.forEach((topic, tIdx) => {
          total++;
          if (topicStatuses[`${uIdx}-${tIdx}`] === 'completed') {
            completed++;
          }
        });
      }
    });
    if (total === 0) return 0;
    return Math.round((completed / total) * 100);
  };

  // AI actions trigger
  const runAIAction = (actionType, unit) => {
    setShowAIModal(true);
    setAILoading(true);
    setActiveQuiz(null);
    setAIAskChat([]);
    
    const uTitle = `Unit ${unit.unit_number}: ${unit.title}`;
    const topics = unit.topics || [];

    setTimeout(() => {
      if (actionType === 'explain') {
        setAIModalTitle(`📚 AI Concepts Explanation`);
        setAIModalContent(getAIExplanation(course.course_name, uTitle, topics));
        setAILoading(false);
      } else if (actionType === 'summarize') {
        setAIModalTitle(`📝 AI Syllabus Summary`);
        setAIModalContent(getAISummary(course.course_name, uTitle, topics));
        setAILoading(false);
      } else if (actionType === 'quiz') {
        setAIModalTitle(`⚡ Dynamic Quiz Builder`);
        const quizObj = getAIQuiz(course.course_name, uTitle, topics);
        setActiveQuiz(quizObj);
        setSelectedAnswers({});
        setQuizSubmitted(false);
        setAILoading(false);
      } else if (actionType === 'studyplan') {
        setAIModalTitle(`📅 Autonomous Study Scheduler`);
        setAIModalContent('');
        
        // Simulating calendar schedule creation
        const planEvents = topics.slice(0, 2).map((t, idx) => ({
          date: new Date(new Date().setDate(new Date().getDate() + idx + 1)).toISOString(),
          title: `Study: ${t} (${course.course_code})`
        }));
        
        const currentEvents = JSON.parse(localStorage.getItem('student_events') || '[]');
        localStorage.setItem('student_events', JSON.stringify([...currentEvents, ...planEvents]));
        window.dispatchEvent(new Event('new_event'));

        // Push notification
        const currentNotifs = JSON.parse(localStorage.getItem('student_notifications') || '[]');
        currentNotifs.unshift({
          text: `AI Agent successfully scheduled 2 study sessions for ${course.course_code} - ${unit.title}.`,
          date: new Date().toISOString()
        });
        localStorage.setItem('student_notifications', JSON.stringify(currentNotifs));
        window.dispatchEvent(new Event('new_notification'));

        setAIModalContent(`### 📅 Study Plan Active!
*Academic Planner Agent has successfully processed this unit.*

We have automatically analyzed your curriculum and scheduled **2 focused study sessions** directly on your platform calendar:
1. **${topics[0]}** - Scheduled for tomorrow.
2. **${topics[1]}** - Scheduled for the day after.

*Check your Calendar page to view or modify these entries.*`);
        setAILoading(false);
      } else if (actionType === 'ask') {
        setAIModalTitle(`💬 RAG Knowledge Chat`);
        setCurrentUnitForAsk(unit);
        setAILoading(false);
        setAIAskChat([
          { sender: 'ai', text: `Hi! I am your AI Subject Expert. Ask me anything about "${unit.title}" and I will reference your course syllabus and materials.` }
        ]);
      }
    }, 1200); // realistic agency delay
  };

  const handleSendAsk = (e) => {
    e.preventDefault();
    if (!aiAskQuery.trim() || !currentUnitForAsk) return;

    const userText = aiAskQuery;
    setAIAskChat(prev => [...prev, { sender: 'user', text: userText }]);
    setAIAskQuery('');

    // Simulate RAG answer
    setTimeout(() => {
      const responseText = `Regarding your query about **"${userText}"** in **${currentUnitForAsk.title}**: 
This aligns directly with our unit objectives. In context, this is handled by analyzing the structural constraints and ensuring inputs are formatted correctly under recommended standards. 

*References: ${currentUnitForAsk.resources?.join(', ') || 'Coursebook'}*`;
      setAIAskChat(prev => [...prev, { sender: 'ai', text: responseText }]);
    }, 800);
  };

  if (loading) return (
    <div className="flex items-center justify-center min-h-[400px]">
      <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600" />
    </div>
  );
  
  if (error) return (
    <Card p="p-6" className="bg-red-50 border border-red-200 text-red-700">
      <h3 className="font-bold text-lg">Error Loading Syllabus</h3>
      <p className="text-sm mt-1">{error}</p>
      <Button variant="neutral" className="mt-4 text-xs" onClick={() => navigate('/courses')}>
        ← Back to Courses
      </Button>
    </Card>
  );

  if (!course) return null;

  const pct = getOverallProgress();
  const cat = CATEGORY_MAP[course.category] || { label: 'Course', variant: 'neutral' };

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Back link */}
      <button
        onClick={() => navigate('/courses')}
        className="text-xs text-slate-500 hover:text-blue-600 transition-colors flex items-center gap-1.5 font-semibold"
      >
        ← Back to B.Tech Curriculum
      </button>

      {/* Main Course Header */}
      <Card p="p-6" className="bg-gradient-to-br from-blue-50/60 to-indigo-50/40 border-slate-200/80">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2 flex-wrap">
              <span className="text-xs font-mono font-bold text-blue-600 bg-blue-100/50 px-2 py-0.5 rounded">
                {course.course_code}
              </span>
              <Badge variant={cat.variant}>{cat.label}</Badge>
            </div>
            <h2 className="text-2xl font-bold text-slate-900 leading-tight">
              {course.course_name}
            </h2>
            <p className="text-xs text-slate-500 mt-1">
              Curriculum Core · {course.credits} Credits · 5 Units Structured
            </p>
          </div>

          <div className="w-full md:w-48 bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-100 shadow-sm shrink-0">
            <div className="flex justify-between items-center mb-1">
              <span className="text-[10px] uppercase font-bold text-slate-400">Completion</span>
              <span className="text-sm font-bold text-blue-600">{pct}%</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-2">
              <div
                className="bg-blue-600 h-2 rounded-full transition-all"
                style={{ width: `${pct}%` }}
              />
            </div>
          </div>
        </div>

        {course.description && (
          <p className="mt-4 text-xs text-slate-600 leading-relaxed border-t border-slate-100 pt-3">
            {course.description}
          </p>
        )}
      </Card>

      {/* Accordion Units List */}
      <div className="space-y-4">
        {course.units.map((unit, uIdx) => {
          const isExpanded = expandedUnit === uIdx;
          const unitRoman = uIdx === 0 ? 'I' : uIdx === 1 ? 'II' : uIdx === 2 ? 'III' : uIdx === 3 ? 'IV' : 'V';
          
          return (
            <div
              key={uIdx}
              className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-sm overflow-hidden"
            >
              {/* Accordion Header */}
              <button
                onClick={() => setExpandedUnit(isExpanded ? null : uIdx)}
                className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-50/50 transition-colors"
              >
                <div>
                  <span className="text-[10px] font-bold text-blue-600 tracking-widest uppercase block mb-0.5">
                    Unit {unitRoman}
                  </span>
                  <h3 className="font-bold text-slate-800 dark:text-slate-100 text-sm">
                    {unit.title}
                  </h3>
                </div>
                <span className="text-slate-400 text-sm transition-transform duration-200">
                  {isExpanded ? '▼' : '▶'}
                </span>
              </button>

              {/* Accordion Body */}
              {isExpanded && (
                <div className="px-6 pb-6 pt-2 border-t border-slate-100 dark:border-slate-700 space-y-6">
                  {/* Learning Objectives */}
                  {unit.learning_objectives && (
                    <div className="bg-slate-50 dark:bg-slate-800/40 p-4 rounded-xl border border-slate-100 dark:border-slate-700 text-xs">
                      <p className="font-semibold text-slate-700 dark:text-slate-300 mb-1">🎯 Learning Objectives:</p>
                      <p className="text-slate-600 dark:text-slate-400 italic">"{unit.learning_objectives}"</p>
                    </div>
                  )}

                  {/* Topics List with Selector */}
                  <div className="space-y-3">
                    <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Syllabus Topics & Study Status</p>
                    <div className="grid gap-3">
                      {unit.topics?.map((topic, tIdx) => {
                        const statusVal = topicStatuses[`${uIdx}-${tIdx}`] || 'not_started';
                        return (
                          <div
                            key={tIdx}
                            className={`p-3.5 rounded-xl border transition-all flex items-center justify-between gap-4 ${
                              statusVal === 'completed' 
                                ? 'bg-emerald-50/30 border-emerald-200 text-slate-800' 
                                : statusVal === 'in_progress'
                                ? 'bg-amber-50/20 border-amber-200 text-slate-800'
                                : 'bg-white border-slate-200 text-slate-800'
                            }`}
                          >
                            <div>
                              <p className="text-xs font-semibold text-slate-900">{topic}</p>
                              {unit.subtopics && unit.subtopics[tIdx] && (
                                <p className="text-[10px] text-slate-500 mt-0.5">
                                  Includes: {unit.subtopics[tIdx]}
                                </p>
                              )}
                            </div>
                            
                            {/* Status Pill Select */}
                            <div className="flex items-center gap-1">
                              <select
                                value={statusVal}
                                onChange={(e) => handleStatusChange(uIdx, tIdx, e.target.value)}
                                className={`text-[10px] font-bold rounded-lg border px-2 py-1 focus:outline-none ${
                                  statusVal === 'completed'
                                    ? 'bg-emerald-100 text-emerald-700 border-emerald-200'
                                    : statusVal === 'in_progress'
                                    ? 'bg-amber-100 text-amber-700 border-amber-200'
                                    : 'bg-slate-100 text-slate-600 border-slate-200'
                                }`}
                              >
                                <option value="not_started">⚪ Not Started</option>
                                <option value="in_progress">🟡 In Progress</option>
                                <option value="completed">🟢 Completed</option>
                              </select>
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </div>

                  {/* Recommended Resources */}
                  {unit.resources && unit.resources.length > 0 && (
                    <div className="text-xs">
                      <p className="font-semibold text-slate-700 dark:text-slate-300 mb-1.5">📚 Recommended Resources:</p>
                      <ul className="list-disc list-inside space-y-1 text-slate-500">
                        {unit.resources.map((res, rIdx) => (
                          <li key={rIdx}>{res}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* AI Study Assistant Panel */}
                  <Card p="p-4" className="bg-slate-900 text-white border-none shadow-md overflow-hidden relative">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-blue-600/10 rounded-full blur-2xl" />
                    
                    <div className="flex items-center gap-2 mb-3">
                      <span className="text-base">✨</span>
                      <h4 className="font-bold text-xs uppercase tracking-wider text-blue-400">Smart AI Study Agent</h4>
                    </div>
                    
                    <p className="text-[11px] text-slate-300 mb-4 leading-relaxed">
                      Leverage context-specific RAG models to review, plan, or test your comprehension of this unit syllabus.
                    </p>

                    <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
                      <button
                        onClick={() => runAIAction('explain', unit)}
                        className="py-2 px-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-[10px] font-bold transition-all flex flex-col items-center gap-1.5 text-center border border-white/10"
                      >
                        <span>🧠</span>
                        <span>Explain Concepts</span>
                      </button>
                      <button
                        onClick={() => runAIAction('summarize', unit)}
                        className="py-2 px-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-[10px] font-bold transition-all flex flex-col items-center gap-1.5 text-center border border-white/10"
                      >
                        <span>📝</span>
                        <span>Summarize Unit</span>
                      </button>
                      <button
                        onClick={() => runAIAction('quiz', unit)}
                        className="py-2 px-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-[10px] font-bold transition-all flex flex-col items-center gap-1.5 text-center border border-white/10"
                      >
                        <span>⚡</span>
                        <span>Practice Quiz</span>
                      </button>
                      <button
                        onClick={() => runAIAction('studyplan', unit)}
                        className="py-2 px-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-[10px] font-bold transition-all flex flex-col items-center gap-1.5 text-center border border-white/10"
                      >
                        <span>📅</span>
                        <span>Schedule Study</span>
                      </button>
                      <button
                        onClick={() => runAIAction('ask', unit)}
                        className="py-2 px-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-[10px] font-bold transition-all flex flex-col items-center gap-1.5 text-center border border-white/10 col-span-2 sm:col-span-1"
                      >
                        <span>💬</span>
                        <span>Ask AI Agent</span>
                      </button>
                    </div>
                  </Card>
                </div>
              )}
            </div>
          )
        })}
      </div>

      {/* AI Assistant Overlay Modal */}
      {showAIModal && (
        <Modal
          isOpen={showAIModal}
          onClose={() => {
            setShowAIModal(false);
            setActiveQuiz(null);
            setAIAskChat([]);
          }}
          title={aiModalTitle}
        >
          {aiLoading ? (
            <div className="py-12 flex flex-col items-center justify-center gap-3">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
              <p className="text-xs text-slate-500 font-medium">Smart Academic Agent fetching RAG models...</p>
            </div>
          ) : (
            <div className="space-y-4 max-h-[60vh] overflow-y-auto pr-1">
              
              {/* Text Markdown Explanations / Summaries */}
              {aiModalContent && (
                <div className="prose prose-slate max-w-none text-xs text-slate-700 leading-relaxed whitespace-pre-line">
                  {aiModalContent}
                </div>
              )}

              {/* Dynamic Interactive Quiz */}
              {activeQuiz && (
                <div className="space-y-5">
                  <p className="text-xs text-slate-500">Answer the following questions generated from your unit syllabus:</p>
                  
                  {activeQuiz.questions.map((q, qIdx) => (
                    <Card key={qIdx} p="p-4" className="border-slate-100 bg-slate-50/50">
                      <p className="font-bold text-slate-900 text-xs mb-3">
                        {qIdx + 1}. {q.question}
                      </p>
                      <div className="space-y-2">
                        {q.options.map((opt, oIdx) => {
                          const isSelected = selectedAnswers[qIdx] === oIdx;
                          const showCorrect = quizSubmitted && oIdx === q.answer;
                          const showWrong = quizSubmitted && isSelected && oIdx !== q.answer;
                          
                          return (
                            <label
                              key={oIdx}
                              className={`flex items-center gap-3 p-2.5 rounded-xl cursor-pointer border text-xs transition-all ${
                                showCorrect
                                  ? 'bg-emerald-50 border-emerald-300 text-emerald-800 font-medium'
                                  : showWrong
                                  ? 'bg-red-50 border-red-300 text-red-800 font-medium'
                                  : isSelected
                                  ? 'bg-blue-50 border-blue-300 text-blue-800 font-medium'
                                  : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50'
                              }`}
                            >
                              <input
                                type="radio"
                                name={`modal-quiz-q-${qIdx}`}
                                disabled={quizSubmitted}
                                checked={isSelected}
                                onChange={() => setSelectedAnswers(prev => ({ ...prev, [qIdx]: oIdx }))}
                                className="text-blue-600 focus:ring-blue-500"
                              />
                              <span>{opt}</span>
                            </label>
                          )
                        })}
                      </div>
                      
                      {quizSubmitted && (
                        <div className="mt-3 text-[10px] text-slate-500 bg-white p-2.5 rounded-lg border border-slate-100">
                          💡 <strong>Explanation:</strong> {q.explanation}
                        </div>
                      )}
                    </Card>
                  ))}

                  {!quizSubmitted ? (
                    <Button
                      variant="primary"
                      className="w-full justify-center text-xs py-2.5"
                      onClick={() => setQuizSubmitted(true)}
                      disabled={Object.keys(selectedAnswers).length < activeQuiz.questions.length}
                    >
                      ✓ Submit Answers
                    </Button>
                  ) : (
                    <div className="flex gap-2">
                      <Button
                        variant="neutral"
                        className="flex-1 justify-center text-xs"
                        onClick={() => {
                          setSelectedAnswers({});
                          setQuizSubmitted(false);
                        }}
                      >
                        Reset Quiz
                      </Button>
                      <Button
                        variant="primary"
                        className="flex-1 justify-center text-xs"
                        onClick={() => setShowAIModal(false)}
                      >
                        Close Modal
                      </Button>
                    </div>
                  )}
                </div>
              )}

              {/* RAG Knowledge Chat */}
              {aiAskChat.length > 0 && (
                <div className="space-y-4">
                  <div className="space-y-3 min-h-[200px] max-h-[300px] overflow-y-auto bg-slate-50 p-3 rounded-xl border border-slate-100">
                    {aiAskChat.map((msg, mIdx) => (
                      <div
                        key={mIdx}
                        className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        <div
                          className={`max-w-[85%] rounded-2xl p-3 text-xs leading-relaxed ${
                            msg.sender === 'user'
                              ? 'bg-blue-600 text-white rounded-br-none'
                              : 'bg-white text-slate-800 border border-slate-100 rounded-bl-none shadow-sm'
                          }`}
                        >
                          {msg.text}
                        </div>
                      </div>
                    ))}
                  </div>

                  <form onSubmit={handleSendAsk} className="flex gap-2">
                    <div className="flex-1">
                      <Input
                        type="text"
                        placeholder="Ask a question about this unit syllabus..."
                        value={aiAskQuery}
                        onChange={(e) => setAIAskQuery(e.target.value)}
                      />
                    </div>
                    <Button type="submit" variant="primary" className="text-xs">
                      Send
                    </Button>
                  </form>
                </div>
              )}

            </div>
          )}
        </Modal>
      )}
    </div>
  )
}
